FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/FlightService.Idp/FlightService.Idp.csproj", "src/FlightService.Idp/"]
RUN dotnet restore "src/FlightService.Idp/FlightService.Idp.csproj"
COPY . .
WORKDIR "/src/src/FlightService.Idp"
RUN dotnet build "FlightService.Idp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FlightService.Idp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FlightService.Idp.dll"]