FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/FlightService.Api/FlightService.Api.csproj", "src/FlightService.Api/"]
RUN dotnet restore "src/FlightService.Api/FlightService.Api.csproj"
COPY . .
WORKDIR "/src/src/FlightService.Api"
RUN dotnet build "FlightService.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FlightService.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FlightService.Api.dll"]